const INTERNAL_API_PATHS = {
  BATCH_CALLBACK: '/batch/callback',
  BATCH_STATUS: '/batch/status/:batchId',
  CACHE_STATS: '/cache/stats',
  CACHE_ENTRIES: '/cache/entries',
  CACHE_CLEAR: '/cache/clear',
  CACHE_CLEANUP: '/cache/cleanup',
  CONFIG_AI: '/config/ai',
  CONFIG_CACHE: '/config/cache',
  CONFIG_QUEUES: '/config/queues',
  CONFIG_OAUTH: '/config/oauth',
  CONFIG_OBJECT_STORAGE: '/config/object-storage',
  CONFIG_WS: '/config/ws',
  STATUS_OPENAI: '/status/openai',
  CONFIG_CATEGORIES: '/config/categories',
  CONFIG_AI_MODEL_OPTIONS: '/config/ai-model-options',
  CONFIG_BATCH_SIZES: '/config/batch-sizes',
  CONFIG_EXCLUDE_LISTS: '/config/exclude-lists',
  DELETE_COMMERCE_DATA: '/delete-commerce-data',
  DELETE_CHANNEL_COMMERCE_DATA: '/delete-channel-commerce-data',
  EXPORT_COMMERCE_DATA: '/export-commerce-data',
  GENERATE_WORKFLOW: '/generate/workflow',
  GET_CATALOGS: '/get-catalogs',
  GET_CHANNELS: '/get-channels',
  GET_CURRENCIES: '/get-currencies',
  GET_LANGUAGES: '/get-languages',
  GET_WAREHOUSES: '/get-warehouses',
  HEALTH: '/health',
  HEALTH_DETAILED: '/health/detailed',
  HEALTH_READY: '/health/ready',
  HEALTH_LIVE: '/health/live',
  HEALTH_SHUTDOWN: '/health/shutdown',
  IMPORT_COMMERCE_DATA: '/import-commerce-data',
  QUEUE_STATS: '/queue/stats',
  JOBS: '/jobs/:jobId',
  WORKFLOW_SESSIONS: '/workflows/sessions',
  WORKFLOW_BATCHES: '/workflows/batches/:sessionId',
  WORKFLOW_SUMMARY: '/workflows/sessions/:sessionId/summary',
  WORKFLOW_SESSION_CONTEXT: '/workflows/sessions/:sessionId/context',
  WORKFLOW_CLEAR_ALL: '/workflows/clear-all',
  WORKFLOW_CLEANUP: '/workflows/cleanup',
};

module.exports = { INTERNAL_API_PATHS };
