const { createERC } = require('../../../utils/misc.cjs');
const { ERC_PREFIX } = require('../../../utils/constants.cjs');

module.exports = async function resetCatalogConfiguration(
  { liferay, logger, persistence },
  { config, options, session, sessionId }
) {
  const catalogId = parseInt(config.catalogId, 10);
  logger.info(`Resetting catalog configuration for catalog ${catalogId}`, {
    sessionId,
    session,
  });

  try {
    // 1. Fetch all price lists for the target catalog
    const res = await liferay.getPriceLists(config, {
      catalogId,
      pageSize: 1000,
      ignoreExclusions: true, // We need to see system/master lists
    });

    const allLists = res.items || [];

    // 2. Identify Master Price List and Master Promotion
    // We look for lists that are NOT generated by AICA (don't have AICA prefix in ERC or name)
    // and ideally have "Master" or "Default" in their name.
    const masterPriceList =
      allLists.find(
        (pl) =>
          pl.type === 'price-list' &&
          !pl.externalReferenceCode?.startsWith('AICA-') &&
          (pl.name.toLowerCase().includes('master') ||
            pl.name.toLowerCase().includes('default'))
      ) ||
      allLists.find(
        (pl) =>
          pl.type === 'price-list' &&
          !pl.externalReferenceCode?.startsWith('AICA-')
      );

    const masterPromotion =
      allLists.find(
        (pl) =>
          pl.type === 'promotion' &&
          !pl.externalReferenceCode?.startsWith('AICA-') &&
          (pl.name.toLowerCase().includes('master') ||
            pl.name.toLowerCase().includes('default'))
      ) ||
      allLists.find(
        (pl) =>
          pl.type === 'promotion' &&
          !pl.externalReferenceCode?.startsWith('AICA-')
      );

    const masterPriceListId = masterPriceList?.id;
    const masterPromotionId = masterPromotion?.id;

    if (!masterPriceListId || !masterPromotionId) {
      logger.warn(
        `Dynamic master identification incomplete for catalog ${catalogId}. ` +
          `Found PriceList: ${masterPriceListId || 'MISSING'}, Promotion: ${masterPromotionId || 'MISSING'}.`,
        { sessionId }
      );
    }

    // 3. Restore Master Lists as Base via Pricing V2.0 API
    // Instead of patching the Catalog (V1.0), we patch the PriceLists themselves (V2.0)
    // Marking a list as base will automatically unset any other base list of the same type for that catalog.

    if (masterPriceListId) {
      logger.info(
        `Restoring master Price List ${masterPriceListId} (${masterPriceList.name}) as base...`,
        { sessionId }
      );
      await liferay.patchPriceList(config, masterPriceListId, {
        catalogBasePriceList: true,
      });
    }

    if (masterPromotionId) {
      logger.info(
        `Restoring master Promotion ${masterPromotionId} (${masterPromotion.name}) as base...`,
        { sessionId }
      );
      await liferay.patchPriceList(config, masterPromotionId, {
        catalogBasePriceList: true,
      });
    }

    logger.info('Catalog reset completed via Pricing V2.0 API.', { sessionId });

    return { success: true };
  } catch (err) {
    logger.error(`Failed to reset catalog configuration: ${err.message}`, {
      sessionId,
      session,
      error: err,
    });
    throw err;
  }
};
