// Three places in this step write the catalog base flag and used to read a 200
// as success: the AICA unset loop below, whose comment promised it "guarantees
// they can be deleted later", and the two master restores. All three reported
// work they did not do. setCatalogBaseFlag reads the value back and says so
// (#790); it lives in utils because the generate side had the same defect
// (#724).
const { setCatalogBaseFlag } = require('../../../utils/catalogBaseFlag.cjs');

module.exports = async function resetCatalogConfiguration(
  { liferay, logger, _persistence },
  { config, _options, session, sessionId }
) {
  let catalogIds = [];

  // Determine which catalogs to process
  if (config.catalogId) {
    catalogIds.push(parseInt(config.catalogId, 10));
  } else {
    try {
      const res = await liferay.getCatalogs(config, { pageSize: 1000 });
      catalogIds = (res.items || []).map((c) => parseInt(c.id, 10));
    } catch (err) {
      logger.warn(`Failed to fetch catalogs for global reset: ${err.message}`, {
        sessionId,
      });
    }
  }

  if (catalogIds.length === 0) {
    logger.info('No catalogs found for configuration reset.', { sessionId });
    return { success: true };
  }

  for (const catalogId of catalogIds) {
    logger.info(`Resetting catalog configuration for catalog ${catalogId}`, {
      sessionId,
      session,
    });

    try {
      // 1. Fetch all price lists for the target catalog
      const res = await liferay.getPriceLists(config, {
        catalogId,
        pageSize: 1000,
        ignoreExclusions: true, // We need to see system/master lists
      });

      const allLists = res.items || [];

      // Ask for the catalogBasePriceList flag to be cleared on AICA lists, so
      // they can be deleted later. It used to say this "guarantees" it; the
      // write does not land on this DXP line (#943), so a list that holds the
      // flag will refuse deletion and setCatalogBaseFlag now says which one.
      const aicaLists = allLists.filter((pl) =>
        pl.externalReferenceCode?.startsWith('AICA-')
      );
      for (const aicaList of aicaLists) {
        if (aicaList.catalogBasePriceList) {
          logger.info(
            `Unsetting catalogBasePriceList for AICA list ${aicaList.id} (${aicaList.name})...`,
            { sessionId }
          );
          await setCatalogBaseFlag(
            { liferay, logger },
            {
              catalogId,
              config,
              desired: false,
              priceListId: aicaList.id,
              sessionId,
              what: 'AICA list',
            }
          );
        }
      }

      // 2. Identify Master Price List and Master Promotion
      // We look for lists that are NOT generated by AICA (don't have AICA prefix in ERC or name)
      // and ideally have "Master" or "Default" in their name.
      const masterPriceList =
        allLists.find(
          (pl) =>
            pl.type === 'price-list' &&
            !pl.externalReferenceCode?.startsWith('AICA-') &&
            (pl.name.toLowerCase().includes('master') ||
              pl.name.toLowerCase().includes('default'))
        ) ||
        allLists.find(
          (pl) =>
            pl.type === 'price-list' &&
            !pl.externalReferenceCode?.startsWith('AICA-')
        );

      const masterPromotion =
        allLists.find(
          (pl) =>
            pl.type === 'promotion' &&
            !pl.externalReferenceCode?.startsWith('AICA-') &&
            (pl.name.toLowerCase().includes('master') ||
              pl.name.toLowerCase().includes('default'))
        ) ||
        allLists.find(
          (pl) =>
            pl.type === 'promotion' &&
            !pl.externalReferenceCode?.startsWith('AICA-')
        );

      const masterPriceListId = masterPriceList?.id;
      const masterPromotionId = masterPromotion?.id;

      if (!masterPriceListId || !masterPromotionId) {
        logger.warn(
          `Dynamic master identification incomplete for catalog ${catalogId}. ` +
            `Found PriceList: ${masterPriceListId || 'MISSING'}, Promotion: ${masterPromotionId || 'MISSING'}.`,
          { sessionId }
        );
      }

      // 3. Restore Master Lists as Base via Pricing V2.0 API
      // Instead of patching the Catalog (V1.0), we patch the PriceLists themselves (V2.0)
      // Marking a list as base will automatically unset any other base list of the same type for that catalog.

      if (masterPriceListId) {
        logger.info(
          `Restoring master Price List ${masterPriceListId} (${masterPriceList.name}) as base...`,
          { sessionId }
        );
        // The patchCatalog call that used to follow this is gone. It sent
        // `catalogBasePriceListId`, which Liferay answers with
        // 400 "The property \"catalogBasePriceListId\" is not defined in
        // Catalog." - measured on 2026.q3.0, as is the promotion equivalent. It
        // was labelled HARDENING and described as invalidating a cache; it has
        // been failing on every delete run for as long as the property has been
        // absent, and it was the call producing the second of the two warnings
        // this step emitted (#790).
        await setCatalogBaseFlag(
          { liferay, logger },
          {
            catalogId,
            config,
            desired: true,
            priceListId: masterPriceListId,
            sessionId,
            what: 'master Price List',
          }
        );
      }

      if (masterPromotionId) {
        logger.info(
          `Restoring master Promotion ${masterPromotionId} (${masterPromotion.name}) as base...`,
          { sessionId }
        );
        await setCatalogBaseFlag(
          { liferay, logger },
          {
            catalogId,
            config,
            desired: true,
            priceListId: masterPromotionId,
            sessionId,
            what: 'master Promotion',
          }
        );
      }

      logger.info(
        `Catalog reset completed via Pricing V2.0 API for catalog ${catalogId}.`,
        { sessionId }
      );
    } catch (err) {
      logger.error(
        `Failed to reset catalog configuration for catalog ${catalogId}: ${err.message}`,
        {
          sessionId,
          session,
          error: err,
        }
      );
      // We don't throw here to allow other catalogs to proceed
    }
  }

  return { success: true };
};
