const { createSandbox } = require('./fixtures/rootScriptSandbox.cjs');

/**
 * `yarn install --frozen-lockfile` exits 0 on a workspace whose member asks for
 * a version the lockfile does not pin: yarn 1 resolves the unsatisfied range,
 * installs it nested under the member, and leaves yarn.lock untouched, so
 * `git diff --exit-code yarn.lock` sees nothing either. `check-lockfile-drift`
 * exists because of that (#920), and it was proved by hand once, in a pull
 * request description that will never run again (#978).
 *
 * These are the cases that separate the check from a script that prints a tick
 * and exits 0. Each one is driven through the real file, copied into a tree of
 * manifests built for it, because the script takes no argument and reads
 * everything relative to its own location.
 */

const lockfile = (...keys) =>
  `${[
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
    '# yarn lockfile v1',
    '',
    ...keys.map((key) => [`"${key}":`, '  version "0.0.0"', ''].join('\n')),
  ].join('\n')}\n`;

const rootManifest = (overrides = {}) => ({
  name: 'sandbox-root',
  private: true,
  version: '0.0.1',
  workspaces: { packages: ['members/alpha'] },
  devDependencies: { prettier: '^3.9.6' },
  ...overrides,
});

const memberManifest = (overrides = {}) => ({
  name: '@sandbox/alpha',
  version: '0.0.1',
  dependencies: { vitest: '5.0.0' },
  ...overrides,
});

describe('check-lockfile-drift: the lockfile describes the manifests (#920, #978)', () => {
  const sandboxes = [];

  const check = (files) => {
    const sandbox = createSandbox('check-lockfile-drift.cjs', files);

    sandboxes.push(sandbox);

    return sandbox.run();
  };

  afterEach(() => {
    while (sandboxes.length) sandboxes.pop().dispose();
  });

  it('passes when every requested range has a lockfile key', () => {
    const result = check({
      'package.json': rootManifest(),
      'members/alpha/package.json': memberManifest(),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('yarn.lock pins every range');
  });

  it('fails when a member asks for a version the lockfile does not pin', () => {
    const result = check({
      'package.json': rootManifest(),
      'members/alpha/package.json': memberManifest({
        dependencies: { vitest: '4.1.11' },
      }),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('members/alpha/package.json');
    expect(result.stderr).toContain('vitest@4.1.11');
  });

  it('fails when the root manifest itself drifts', () => {
    const result = check({
      'package.json': rootManifest({
        devDependencies: { prettier: '^3.10.0' },
      }),
      'members/alpha/package.json': memberManifest(),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('prettier@^3.10.0');
  });

  it('fails when workspaces lists a member that no longer exists', () => {
    const result = check({
      'package.json': rootManifest({
        workspaces: { packages: ['members/alpha', 'members/removed'] },
      }),
      'members/alpha/package.json': memberManifest(),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('members/removed');
    expect(result.stderr).toContain('no package.json');
  });

  it('reads every dependency section, not just dependencies', () => {
    const result = check({
      'package.json': rootManifest({
        optionalDependencies: { '@rollup/rollup-linux-x64-gnu': '4.63.1' },
      }),
      'members/alpha/package.json': memberManifest(),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('@rollup/rollup-linux-x64-gnu@4.63.1');
  });

  it('reads a lockfile entry that satisfies several requested ranges', () => {
    const result = check({
      'package.json': rootManifest({
        devDependencies: { prettier: '^3.9.6' },
      }),
      'members/alpha/package.json': memberManifest({
        dependencies: { prettier: '^3.0.0' },
      }),
      'yarn.lock': lockfile('prettier@^3.9.6", "prettier@^3.0.0'),
    });

    expect(result.status).toBe(0);
  });

  it('does not report a sibling workspace member as unpinned', () => {
    const result = check({
      'package.json': rootManifest({
        workspaces: { packages: ['members/alpha', 'members/beta'] },
      }),
      'members/alpha/package.json': memberManifest({
        dependencies: { vitest: '5.0.0', '@sandbox/beta': '0.0.1' },
      }),
      'members/beta/package.json': memberManifest({
        name: '@sandbox/beta',
        dependencies: {},
      }),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(0);
  });

  it('does not report a range yarn resolves from the filesystem', () => {
    const result = check({
      'package.json': rootManifest(),
      'members/alpha/package.json': memberManifest({
        dependencies: {
          vitest: '5.0.0',
          'local-tool': 'file:../../tools/local-tool',
          'linked-tool': 'link:../../tools/linked-tool',
        },
      }),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(0);
  });

  it('refuses a glob in workspaces rather than silently skipping it', () => {
    const result = check({
      'package.json': rootManifest({
        workspaces: { packages: ['members/*'] },
      }),
      'members/alpha/package.json': memberManifest(),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain('is a glob');
  });

  it('reports every drifted range, not only the first', () => {
    const result = check({
      'package.json': rootManifest({
        devDependencies: { prettier: '^3.10.0' },
      }),
      'members/alpha/package.json': memberManifest({
        dependencies: { vitest: '4.1.11' },
      }),
      'yarn.lock': lockfile('prettier@^3.9.6', 'vitest@5.0.0'),
    });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('2 problem(s)');
  });
});
