const MockDataGenerator = require('../generators/mockDataGenerator.cjs');
const { GenerationFacade } = require('../services/generationFacade.cjs');
const { listSchemaNames } = require('../utils/configurationAssets.cjs');

/**
 * Which contract the mock has to satisfy, and the guard that keeps it there.
 *
 * `GenerationFacade.generateData` selects `mockDataGenerator` in place of
 * `aiService` when `demoMode` is set, then runs the identical standardise ->
 * validate -> product-steps -> import pipeline and validates the result against
 * the same `generation-schemas` entry. The contract is therefore not a matter
 * of preference: mock output must be AI output, and the translation into
 * Liferay's DTOs belongs to the product steps, where live mode performs it.
 *
 * Two assertions per entity, because passing ajv is not on its own enough:
 *
 * 1. The payload survives the real facade with `demoMode: true` - the gate a
 *    demo run actually puts it through, including the standardise pass and the
 *    wrapping rules, not just a schema compiled in isolation here.
 * 2. Every property it emits is declared by the schema. Since #690 the schema
 *    sent to the provider is projected from these files with objects closed, so
 *    a property the generation schema does not declare cannot arrive in live
 *    mode. Anything extra here is demo-only data, and any pipeline behaviour
 *    that depends on it is untested where it matters. Ajv alone will not catch
 *    it: the product item permits additional properties, which is exactly how
 *    `productOptions` and `productSpecifications` - Liferay's names, not the
 *    schema's - rode along unvalidated and sent demo mode down a different
 *    branch of thirteen dual reads than live mode takes.
 *
 * Neither needs an API call or an environment, which is the point: the live
 * E2E suite has not passed in over forty scheduled runs, so this is what stands
 * between mock drift and a defect first seen in real generated data. See #652.
 */

// Generation schemas with no mock behind them, and why. `promo` is generated by
// PromoGenerator calling `ctx.ai` directly rather than through the facade, and
// `pdf` by mediaGenerator, which skips the model itself under `demoMode`.
// Neither routes through MockDataGenerator, so neither has a shape to check.
const NOT_MOCK_GENERATED = ['pdf', 'promo'];

const PRODUCTS = [
  {
    externalReferenceCode: 'AICA-PRD-1',
    skus: [{ sku: 'AICA-SKU-1' }],
  },
];
const ACCOUNTS = [{ externalReferenceCode: 'AICA-ACC-1', id: 4001 }];

// Options chosen to switch on every conditional branch the generators have, so
// the optional payloads - variants, price entries, images, attachments - are
// covered rather than skipped.
const CASES = {
  account: { count: 3, options: { accountType: 'mixed' } },
  order: { count: 3, options: { accounts: ACCOUNTS, products: PRODUCTS } },
  pricing: { count: 3, options: { products: PRODUCTS } },
  product: {
    count: 3,
    options: {
      category: 'Electronics',
      generateBulkPricing: true,
      generatePriceLists: true,
      generateSkuVariants: true,
      imageMode: 'ai',
      pdfMode: 'ai',
    },
  },
  warehouse: { count: 3, options: {} },
};

const REQUEST_CONFIG = { catalogId: 987 };
const SELECTED_LANGUAGES = ['en-US', 'es-ES'];

const TRANSLATED_SHAPE_WARNING = 'generation schema names';

function methodNameFor(entityType) {
  return `generate${entityType[0].toUpperCase()}${entityType.slice(1)}Data`;
}

/**
 * Properties present in the payload that the schema never describes.
 *
 * Open value maps - the locale-keyed ones - are followed into rather than
 * treated as undeclared, since their keys are a runtime choice.
 */
function undeclaredProperties(value, schema, pointer = '') {
  if (!schema || typeof schema !== 'object') return [];

  if (Array.isArray(value)) {
    return schema.items
      ? value.flatMap((entry) =>
          undeclaredProperties(entry, schema.items, `${pointer}/*`)
        )
      : [];
  }

  if (!value || typeof value !== 'object') return [];

  const declared = schema.properties;
  const openValues = schema.additionalProperties;

  return Object.entries(value).flatMap(([key, child]) => {
    if (declared && Object.hasOwn(declared, key)) {
      return undeclaredProperties(child, declared[key], `${pointer}/${key}`);
    }
    if (openValues && typeof openValues === 'object') {
      return undeclaredProperties(child, openValues, `${pointer}/${key}`);
    }
    return declared ? [`${pointer}/${key}`] : [];
  });
}

function describeErrors(errors) {
  return [
    ...new Set(
      (errors || []).map(
        (error) =>
          `${(error.instancePath || '(root)').replace(/\/\d+/g, '/*')} ${
            error.message
          }`
      )
    ),
  ].join('; ');
}

describe('mock generator output satisfies the generation schemas', () => {
  let facade;
  let logger;
  let mock;

  beforeEach(() => {
    logger = { debug: vi.fn(), error: vi.fn(), info: vi.fn(), warn: vi.fn() };
    const ctx = { liferay: {}, logger };
    mock = new MockDataGenerator(ctx);
    ctx.mockDataGenerator = mock;
    ctx.ai = {};
    facade = new GenerationFacade(ctx);
  });

  it('checks every generation schema a mock can produce', () => {
    const schemaNames = listSchemaNames();

    expect(
      schemaNames.filter((name) => !NOT_MOCK_GENERATED.includes(name)),
      'a generation schema was added without a mock case; register it in ' +
        'CASES or record why no mock stands in for it'
    ).toEqual(Object.keys(CASES).sort());

    for (const name of NOT_MOCK_GENERATED) {
      expect(
        typeof mock[methodNameFor(name)],
        `MockDataGenerator now generates ${name}; demo mode will validate it ` +
          `against generation-schemas/${name}.json, so it needs a case here`
      ).not.toBe('function');
    }
  });

  for (const [entityType, { count, options }] of Object.entries(CASES)) {
    describe(entityType, () => {
      const runOptions = () => ({
        ...options,
        demoMode: true,
        selectedLanguages: SELECTED_LANGUAGES,
      });

      it('passes the gate a demo run puts it through', async () => {
        let error;
        const generated = await facade
          .generateData(entityType, count, { ...REQUEST_CONFIG }, runOptions())
          .catch((caught) => {
            error = caught;
          });

        expect(
          error === undefined,
          `demo mode cannot generate ${entityType}: ${error?.message} ` +
            `[${describeErrors(error?.errors)}]`
        ).toBe(true);
        expect(generated).toBeDefined();
      });

      it('emits only properties the schema declares', async () => {
        const schema = require(`../generation-schemas/${entityType}.json`);
        const generated = await mock.generate(
          entityType,
          count,
          { ...REQUEST_CONFIG },
          runOptions()
        );

        const collection = `${entityType}s`;
        const payload = schema.properties[collection]
          ? { [collection]: generated }
          : generated;

        expect(
          [...new Set(undeclaredProperties(payload, schema))],
          `mock ${entityType} data carries properties ` +
            `generation-schemas/${entityType}.json does not declare, so the ` +
            'AI cannot produce them and demo mode is exercising a shape live ' +
            'mode never sees'
        ).toEqual([]);
      });
    });
  }

  it('generates products under the schema names, not Liferay names', async () => {
    const [product] = await facade.generateData(
      'product',
      1,
      { ...REQUEST_CONFIG },
      { ...CASES.product.options, demoMode: true }
    );

    expect(Array.isArray(product.options)).toBe(true);
    expect(Array.isArray(product.specifications)).toBe(true);
    expect(product.productOptions).toBeUndefined();
    expect(product.productSpecifications).toBeUndefined();

    // The facade's own detector, rather than a second opinion about the same
    // thing: if it stays quiet the shape is the one live mode produces.
    expect(
      logger.warn.mock.calls.some(([message]) =>
        String(message).includes(TRANSLATED_SHAPE_WARNING)
      )
    ).toBe(false);
  });

  it('describes option values the way the prompt asks for them', () => {
    const [product] = mock.generateProductData(
      'Electronics',
      1,
      REQUEST_CONFIG,
      null,
      SELECTED_LANGUAGES,
      { generateSkuVariants: true }
    );

    for (const option of product.options) {
      expect(typeof option.name).toBe('string');
      for (const value of option.productOptionValues) {
        expect(typeof value).toBe('string');
      }
    }

    // `skuVariants[].options` stays an option-name-to-value map: it is the one
    // open map schemaProjection cannot expand, and ajv validates it as an
    // object. Any pair-array wire format belongs at the provider boundary.
    for (const variant of product.skuVariants) {
      expect(Array.isArray(variant.options)).toBe(false);
      expect(Object.keys(variant.options).length).toBeGreaterThan(0);
    }
  });

  it('pricing returns the object its schema declares, not a bare array', () => {
    // The drift this file was first written for: `generatePricingData` returned
    // a bare array of `{ skuExternalReferenceCode, price }`.
    const pricing = mock.generatePricingData(PRODUCTS, 'standard', {}, 'm', [
      'en-US',
    ]);

    expect(Array.isArray(pricing)).toBe(false);
    expect(pricing.priceListName).toBeTruthy();
    expect(Array.isArray(pricing.priceEntries)).toBe(true);

    for (const entry of pricing.priceEntries) {
      expect(entry.sku).toBeTruthy();
      expect(entry.externalReferenceCode).toBeTruthy();
      expect(entry.skuExternalReferenceCode).toBeTruthy();
      expect(typeof entry.price).toBe('number');
    }
  });
});
