const fs = require('fs');
const path = require('path');
const { cases } = require('./fixtures/promptCorpus.cjs');
const { PromptService } = require('../services/promptService.cjs');

/**
 * The byte-for-byte corpus.
 *
 * #643 was template syntax reaching the model because the renderer did not
 * understand it. #655 puts a real template engine behind the same renderer, so
 * the same prompts are now parsed by something with its own opinions about
 * whitespace, undefined values, escaping and `{`. Any one of those opinions
 * differing from the old two-regex substitution is #643 again, in the other
 * direction and just as invisible: a prompt is what goes to a paid model, and
 * nothing downstream of here inspects it.
 *
 * So every prompt in `prompts/` is rendered against the contexts in
 * `fixtures/promptCorpus.cjs` and compared to output committed BEFORE the
 * engine was introduced. These files were generated by the old renderer. A
 * difference is a regression until someone proves otherwise, and it has to be
 * reviewed as a diff rather than silently re-baselined.
 *
 * Regenerating is deliberate and visible: `UPDATE_PROMPT_CORPUS=1 yarn test
 * promptRendering`. Only do that when a prompt file itself changed, and read
 * the resulting diff.
 */

const PROMPTS_DIR = path.join(__dirname, '..', 'prompts');
const CORPUS_DIR = path.join(__dirname, 'fixtures', 'prompt-corpus');

const updating = process.env.UPDATE_PROMPT_CORPUS === '1';

const service = new PromptService({});

function readPrompt(name) {
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  return fs.readFileSync(path.join(PROMPTS_DIR, `${name}.md`), 'utf8');
}

function goldenPath({ label, prompt }) {
  return path.join(CORPUS_DIR, `${prompt}.${label}.txt`);
}

function placeholderRoots(template) {
  const roots = new Set();

  for (const [, name] of template.matchAll(/\{\{(?:=json:)?([\w.[\]]+)\}\}/g)) {
    roots.add(name.split(/[.[]/)[0]);
  }

  return roots;
}

const promptFiles = fs
  .readdirSync(PROMPTS_DIR)
  .filter((file) => file.endsWith('.md'))
  .map((file) => path.basename(file, '.md'));

if (updating) {
  fs.mkdirSync(CORPUS_DIR, { recursive: true });
}

describe('prompt corpus', () => {
  it('has a case for every prompt file', () => {
    expect(promptFiles.length).toBeGreaterThan(0);
    expect([...new Set(cases.map((one) => one.prompt))].sort()).toEqual(
      promptFiles.sort()
    );
  });

  it.each(promptFiles)('%s exercises every placeholder it contains', (name) => {
    const covered = new Set();

    for (const one of cases.filter((entry) => entry.prompt === name)) {
      for (const [key, value] of Object.entries(one.vars)) {
        if (value !== '' && value !== null && value !== undefined) {
          covered.add(key);
        }
      }
    }

    for (const root of placeholderRoots(readPrompt(name))) {
      expect(covered).toContain(root);
    }
  });

  it.each(cases.map((one) => [`${one.prompt}.${one.label}`, one]))(
    '%s renders byte for byte as committed',
    (_id, one) => {
      const rendered = service.renderFromString(
        readPrompt(one.prompt),
        one.vars,
        one.prompt
      );

      if (updating) {
        // eslint-disable-next-line security/detect-non-literal-fs-filename
        fs.writeFileSync(goldenPath(one), rendered);
      }

      // eslint-disable-next-line security/detect-non-literal-fs-filename
      expect(fs.readFileSync(goldenPath(one), 'utf8')).toBe(rendered);
    }
  );

  // Replaces the #643 test that asserted the prompt *files* contain no
  // unsupported syntax. They may now, so what matters is that nothing survives
  // the render.
  it.each(cases.map((one) => [`${one.prompt}.${one.label}`, one]))(
    '%s leaves no template syntax in what the model receives',
    (_id, one) => {
      const rendered = service.renderFromString(
        readPrompt(one.prompt),
        one.vars,
        one.prompt
      );

      expect(rendered).not.toMatch(/\{\{/);
      expect(rendered).not.toMatch(/\{%/);
    }
  );
});
