const path = require('path');

const SCRIPT = path.resolve(
  __dirname,
  '../../../scripts/read-oauth-credentials.cjs'
);

/**
 * Liferay exposes no API for creating an OAuth2 application, so one that must
 * exist in every freshly built instance is declared as a client extension and
 * its credentials are generated by Liferay. They reach a caller through the
 * routes tree, which this script reads (#988).
 *
 * The failure paths matter as much as the success one: a run that proceeds with
 * an empty credential fails much later, as a 403 that looks like a policy
 * decision rather than a missing deployment.
 */

const ERC = 'ai-commerce-accelerator-cli-automation';

// The shape `@rotty3000/config-node` reads: a flat map of configuration keys,
// with the external reference codes enumerated under a well-known one.
const routesTree = (erc, { clientId, clientSecret, tokenUri }) => ({
  'liferay.oauth.application.external.reference.codes': [erc],
  [`${erc}.oauth2.headless.server.client.id`]: clientId,
  [`${erc}.oauth2.headless.server.client.secret`]: clientSecret,
  [`${erc}.oauth2.token.uri`]: tokenUri,
});

const DEP = require.resolve('@rotty3000/config-node');

// The script requires its dependency at load time, so a vitest module mock does
// not reach it. Planting the stub in Node's own CJS cache before the script is
// loaded does, and keeps the test exercising the real script rather than a
// re-implementation of it.
const loadScript = (config) => {
  const lxcConfig = {
    oauthApplication: (erc) => {
      if (config === null) {
        // What the real library does with no routes tree: it calls .includes on
        // an undefined list.
        throw new TypeError(
          "Cannot read properties of undefined (reading 'includes')"
        );
      }

      const ercs =
        config['liferay.oauth.application.external.reference.codes'] || [];

      if (!ercs.includes(erc)) return undefined;

      return {
        clientId: () => config[`${erc}.oauth2.headless.server.client.id`],
        clientSecret: () =>
          config[`${erc}.oauth2.headless.server.client.secret`],
        tokenUri: () => config[`${erc}.oauth2.token.uri`],
      };
    },
  };

  require.cache[DEP] = {
    id: DEP,
    filename: DEP,
    loaded: true,
    exports: { lxcConfig },
  };

  delete require.cache[require.resolve(SCRIPT)];
  return require(SCRIPT);
};

afterEach(() => {
  delete require.cache[DEP];
  delete require.cache[require.resolve(SCRIPT)];
});

describe('read-oauth-credentials', () => {
  describe('argument parsing', () => {
    it('takes the external reference code positionally', () => {
      const { parseArgs } = loadScript({});

      expect(parseArgs([ERC])).toMatchObject({ erc: ERC, json: false });
    });

    it('accepts --json and both --prefix forms', () => {
      const { parseArgs } = loadScript({});

      expect(parseArgs([ERC, '--json'])).toMatchObject({ json: true });
      expect(parseArgs([ERC, '--prefix', 'OTHER'])).toMatchObject({
        prefix: 'OTHER',
      });
      expect(parseArgs([ERC, '--prefix=OTHER'])).toMatchObject({
        prefix: 'OTHER',
      });
    });

    it('does not mistake a prefix value for the reference code', () => {
      const { parseArgs } = loadScript({});

      expect(parseArgs(['--prefix', 'OTHER', ERC]).erc).toBe(ERC);
    });

    it('defaults the prefix to the variables the CLI reads', () => {
      const { parseArgs } = loadScript({});

      expect(parseArgs([ERC]).prefix).toBe('AICA_ADMIN_CLIENT');
    });
  });

  describe('reading', () => {
    it('returns the credentials a declared application published', () => {
      const { readCredentials } = loadScript(
        routesTree(ERC, {
          clientId: 'id-automation',
          clientSecret: 'shh',
          tokenUri: 'http://localhost:8080/o/oauth2/token',
        })
      );

      expect(readCredentials(ERC)).toEqual({
        clientId: 'id-automation',
        clientSecret: 'shh',
        tokenUri: 'http://localhost:8080/o/oauth2/token',
      });
    });

    // An environment that was never wired up, distinct from a deployment that
    // failed - the remedies are different and the messages say so.
    it('reports an unreadable routes tree distinctly', () => {
      const { readCredentials } = loadScript(null);
      const result = readCredentials(ERC);

      expect(result.error).toMatch(/routes tree is not readable/);
      expect(result.error).toMatch(/LIFERAY_ROUTES_CLIENT_EXTENSION/);
      expect(result.clientId).toBeUndefined();
    });

    it('reports a readable tree that does not list the application', () => {
      const { readCredentials } = loadScript(
        routesTree('some-other-extension', {
          clientId: 'x',
          clientSecret: 'y',
          tokenUri: 'z',
        })
      );
      const result = readCredentials(ERC);

      expect(result.error).toMatch(/does not list/);
      expect(result.error).not.toMatch(/not readable/);
    });

    // A user-agent application resolves a client id and no secret. Returning
    // that half-filled would be sent as an exchange that fails at Liferay.
    it('refuses an application with no secret', () => {
      const { readCredentials } = loadScript(
        routesTree(ERC, {
          clientId: 'id-user-agent',
          clientSecret: undefined,
          tokenUri: 'http://localhost:8080/o/oauth2/token',
        })
      );

      expect(readCredentials(ERC).error).toMatch(/no client credentials/);
    });

    it('refuses an application with no client id', () => {
      const { readCredentials } = loadScript(
        routesTree(ERC, {
          clientId: undefined,
          clientSecret: 'shh',
          tokenUri: 'http://localhost:8080/o/oauth2/token',
        })
      );

      expect(readCredentials(ERC).error).toMatch(/no client credentials/);
    });
  });
});
