const { jsPDF } = require('jspdf');
const { ObjectStorageService } = require('./objectStorage.cjs');
const { v4: uuidv4 } = require('uuid');

class PDFGenerator {
  constructor() {
    this.objectStorage = new ObjectStorageService();
  }

  async generateProductPDF(pdfContent, productSku) {
    try {
      // Create new PDF document with explicit options to ensure compatibility
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'pt',
        format: 'a4',
        hotfixes: ['px_scaling']
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 40;
      const maxWidth = pageWidth - margin * 2;
      let currentY = margin;

      // Ensure we have valid content
      const title = pdfContent?.title || `Product Documentation - ${productSku}`;
      const sections = pdfContent?.sections || [
        {
          title: 'Product Information',
          content: `This is a sample product documentation for ${productSku}. This document contains basic product information and specifications.`
        }
      ];

      // Add title
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      const titleLines = doc.splitTextToSize(title, maxWidth);
      titleLines.forEach(line => {
        doc.text(line, margin, currentY);
        currentY += 30;
      });
      currentY += 20;

      // Add each section
      for (const section of sections) {
        // Check if we need a new page
        if (currentY > pageHeight - 100) {
          doc.addPage();
          currentY = margin;
        }

        // Section title
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        const sectionTitle = section.title || 'Section';
        doc.text(sectionTitle, margin, currentY);
        currentY += 25;

        // Section content
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');

        const content = section.content || 'Content not available.';
        const lines = doc.splitTextToSize(content, maxWidth);
        for (const line of lines) {
          if (currentY > pageHeight - 80) {
            doc.addPage();
            currentY = margin;
          }
          doc.text(line, margin, currentY);
          currentY += 15;
        }
        currentY += 20; // Space between sections
      }

      // Add footer to all pages
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(
          `Generated by Liferay AI Data Generator - Page ${i} of ${pageCount}`,
          margin,
          pageHeight - 30
        );
        doc.text(`Product SKU: ${productSku}`, pageWidth - margin - 120, pageHeight - 30);
      }

      // Use datauri string instead of arraybuffer for better compatibility
      const pdfOutput = doc.output('datauri');

      // Convert datauri to buffer
      const base64Data = pdfOutput.split(',')[1];
      return Buffer.from(base64Data, 'base64');
    } catch (error) {
      console.error('Error generating PDF:', error);
      throw error;
    }
  }

  async uploadPDFToStorage(uploadURL, pdfBuffer, filename) {
    try {
      // Upload PDF to object storage
      const response = await fetch(uploadURL, {
        method: 'PUT',
        body: pdfBuffer,
        headers: {
          'Content-Type': 'application/pdf',
          'Connection': 'keep-alive',
        },
        // Set a timeout for the request
        signal: AbortSignal.timeout(60000), // 60 second timeout
      });

      if (!response.ok) {
        throw new Error(`Failed to upload PDF: ${response.statusText} (Status: ${response.status})`);
      }

      // Normalize the path for object entity access
      const objectPath =
        this.objectStorage.normalizeObjectEntityPath(uploadURL);

      return {
        objectPath,
        uploadURL,
        filename,
      };
    } catch (error) {
      console.error('Error uploading PDF:', error);
      // It's good practice to re-throw the error after logging if the caller needs to handle it
      throw error;
    }
  }

  async generateAndUploadProductPDF(productData, productSku) {
    try {
      console.log(`Generating PDF for product: ${productSku}`);

      const pdfBuffer = await this.generateProductPDF(productData, productSku);

      // Validate PDF buffer
      if (!pdfBuffer || pdfBuffer.length === 0) {
        throw new Error('Generated PDF buffer is empty');
      }

      // Check if PDF starts with proper PDF header
      const pdfHeader = pdfBuffer.slice(0, 4).toString();
      if (pdfHeader !== '%PDF') {
        throw new Error('Generated PDF does not have valid PDF header');
      }

      // Store in object storage
      console.log(`Uploading PDF to object storage...`);
      const objectKey = `product-pdfs/${productSku}-${Date.now()}.pdf`;
      const uploadResult = await this.objectStorage.uploadFile(objectKey, pdfBuffer, 'application/pdf');

      console.log(`✓ PDF generated and uploaded successfully for ${productSku}`);

      return {
        objectPath: uploadResult.objectPath,
        fileName: `${productSku}_product_manual.pdf`,
        buffer: pdfBuffer
      };
    } catch (error) {
      console.error(`Failed to generate PDF for ${productSku}:`, error);
      throw error;
    }
  }

  // Determine which products should get PDFs based on ratio (deterministic selection)
  selectProductsForPDFs(products, ratio) {
    if (ratio <= 0 || ratio > 100) return [];

    const count = Math.ceil(products.length * (ratio / 100));
    
    // Deterministic selection based on stable sort by externalReferenceCode
    const sortedProducts = [...products].sort((a, b) => {
      const aRef = a.externalReferenceCode || a.sku || `product-${products.indexOf(a)}`;
      const bRef = b.externalReferenceCode || b.sku || `product-${products.indexOf(b)}`;
      return aRef.localeCompare(bRef);
    });
    return sortedProducts.slice(0, count);
  }

  // Determine which products should get images based on ratio (deterministic selection)
  selectProductsForImages(products, ratio) {
    if (ratio <= 0 || ratio > 100) return [];

    const count = Math.ceil(products.length * (ratio / 100));
    
    // Deterministic selection based on stable sort by externalReferenceCode
    const sortedProducts = [...products].sort((a, b) => {
      const aRef = a.externalReferenceCode || a.sku || `product-${products.indexOf(a)}`;
      const bRef = b.externalReferenceCode || b.sku || `product-${products.indexOf(b)}`;
      return aRef.localeCompare(bRef);
    });
    return sortedProducts.slice(0, count);
  }
}

module.exports = { PDFGenerator };