name: Fetch Logs
on: workflow_dispatch
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Logs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh run view 28950981266 --log-failed
